### ISSUE TITLE
Token validation fail

### ISSUE THREAD

**Issue by DedalusOsX** [Draper-University/DHN-back#3]
I've tried to create a news item - but got permission denied! Debugged with console.log on backend and apparently your function throws an invalid token

`{ JsonWebTokenError: invalid token
    at Object.module.exports [as verify] (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/jsonwebtoken/verify.js:75:17)
    at Function.checkToken (/Users/arturaslanyan/repos/dhn/dhn-back/src/common/auth.ts:53:13)
    at verifyToken (/Users/arturaslanyan/repos/dhn/dhn-back/src/common/auth.ts:41:14)
    at Layer.handle [as handle_request] (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/route.js:131:14)
    at Route.dispatch (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/layer.js:95:5)
    at /Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:317:13)
    at /Users/arturaslanyan/repos/dhn/dhn-back/node_modules/express/lib/router/index.js:284:7 name: 'JsonWebTokenError', message: 'invalid token' }`

**Comment by gharibyan** [comment]
Not backend related
